namespace StudyLife.Shared;

/// <summary>A single proposed (not yet saved) study session generated by the exam or weekly planner.</summary>
public class PlanProposal
{
    public int CourseId { get; set; }
    public string CourseName { get; set; } = "";
    public string CourseColor { get; set; } = "#6C5CE7";
    public string? Topic { get; set; }
    public DateTime Start { get; set; }
    public DateTime End { get; set; }
}

/// <summary>
/// Pure calculation helpers behind the exam backward-planner and weekly-plan assistant
/// (Client/Pages/Planner.razor, Server/Controllers/PlannerController.cs for the Home
/// Assistant service). Lives in Shared - not Client - because both the browser UI and the
/// server-side HA endpoint need the identical slot-finding/weighting logic without
/// depending on either side's session model, so it operates on plain (Start, End) tuples.
/// </summary>
public static class StudyPlanner
{
    public const int DefaultDayStartHour = 8;
    public const int DefaultDayEndHour = 21;

    private static readonly HashSet<DayOfWeek> AllDays = new()
    {
        DayOfWeek.Sunday, DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday,
        DayOfWeek.Thursday, DayOfWeek.Friday, DayOfWeek.Saturday,
    };

    /// <summary>Parses the comma-separated UserSettings.StudyDays list (0=Sunday..6=Saturday, .NET DayOfWeek values)
    /// into a set. Empty/invalid falls back to "all days allowed" (behavior before this setting was introduced).</summary>
    public static HashSet<DayOfWeek> ParseStudyDays(string? csv)
    {
        if (string.IsNullOrWhiteSpace(csv)) return new HashSet<DayOfWeek>(AllDays);
        var result = new HashSet<DayOfWeek>();
        foreach (var part in csv.Split(',', StringSplitOptions.RemoveEmptyEntries))
            if (int.TryParse(part, out var n) && n is >= 0 and <= 6) result.Add((DayOfWeek)n);
        return result.Count > 0 ? result : new HashSet<DayOfWeek>(AllDays);
    }

    /// <summary>
    /// Finds free time slots of at least <paramref name="slotLength"/> between
    /// <paramref name="fromDate"/> (inclusive, exact time is respected) and
    /// <paramref name="toDate"/> (inclusive, whole day), within the daily window
    /// [<paramref name="dayStartHour"/>, <paramref name="dayEndHour"/>) while avoiding
    /// overlaps with <paramref name="busyIntervals"/>. Days whose weekday is not in
    /// <paramref name="allowedDays"/> are skipped entirely (null = all days allowed).
    /// Stops as soon as <paramref name="maxTotalSlots"/> proposals have been found.
    /// </summary>
    public static List<(DateTime Start, DateTime End)> FindFreeSlots(
        DateTime fromDate,
        DateTime toDate,
        IEnumerable<(DateTime Start, DateTime End)> busyIntervals,
        TimeSpan slotLength,
        int maxSlotsPerDay,
        int maxTotalSlots,
        int dayStartHour = DefaultDayStartHour,
        int dayEndHour = DefaultDayEndHour,
        IReadOnlySet<DayOfWeek>? allowedDays = null)
    {
        var result = new List<(DateTime, DateTime)>();
        if (maxTotalSlots <= 0 || toDate.Date < fromDate.Date || dayEndHour <= dayStartHour) return result;

        var busy = busyIntervals.OrderBy(b => b.Start).ToList();
        var day = fromDate.Date;
        while (day <= toDate.Date && result.Count < maxTotalSlots)
        {
            if (allowedDays != null && !allowedDays.Contains(day.DayOfWeek))
            {
                day = day.AddDays(1);
                continue;
            }

            var dayEnd = day.AddHours(dayEndHour);
            var cursor = day.AddHours(dayStartHour);
            if (day == fromDate.Date && fromDate > cursor) cursor = RoundUpToNextHalfHour(fromDate);

            var slotsToday = 0;
            while (slotsToday < maxSlotsPerDay && result.Count < maxTotalSlots && cursor + slotLength <= dayEnd)
            {
                var slotEnd = cursor + slotLength;
                DateTime? conflictEnd = null;
                foreach (var b in busy)
                {
                    if (b.Start < slotEnd && b.End > cursor) { conflictEnd = b.End; break; }
                }
                if (conflictEnd.HasValue)
                {
                    cursor = RoundUpToNextHalfHour(conflictEnd.Value);
                    continue;
                }
                result.Add((cursor, slotEnd));
                slotsToday++;
                cursor = slotEnd.AddMinutes(30); // small buffer between two proposals on the same day
            }
            day = day.AddDays(1);
        }
        return result;
    }

    private static DateTime RoundUpToNextHalfHour(DateTime dt)
    {
        var rounded = new DateTime(dt.Year, dt.Month, dt.Day, dt.Hour, dt.Minute >= 30 ? 30 : 0, 0);
        if (rounded < dt) rounded = rounded.AddMinutes(30);
        return rounded;
    }

    /// <summary>
    /// Distributes <paramref name="totalCount"/> units proportionally to <paramref name="weights"/> across
    /// the respective keys, via "smooth weighted round-robin" (as e.g. nginx uses for load balancing) -
    /// this produces a well-interleaved order instead of "all of A first, then all of B".
    /// </summary>
    public static List<TKey> WeightedRoundRobin<TKey>(Dictionary<TKey, double> weights, int totalCount) where TKey : notnull
    {
        var picks = new List<TKey>();
        if (weights.Count == 0 || totalCount <= 0) return picks;

        var acc = weights.Keys.ToDictionary(k => k, _ => 0.0);
        for (var i = 0; i < totalCount; i++)
        {
            foreach (var key in acc.Keys.ToList()) acc[key] += weights[key];
            var top = acc.OrderByDescending(kv => kv.Value).First().Key;
            picks.Add(top);
            acc[top] -= weights.Values.Sum();
        }
        return picks;
    }
}
