---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: studylife-registry-auth
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgCGvYKIFOCVcgkFLfA46dsqqaRnHLjAKEEUoS43tqX+2ima5bvDafrFodss0jSYhSlHhdL1aSCDECOaPsv+zoQA+MDP28wv0eg7ct+y9d8VG9sMgpq4x0scmMWpAsxu00JK+ucW2+MrD7gWwHCuZ4l/xCPSj85yH3vnJL6pvMM9GgbsN4rxJ9D3g4tuUkpuGDxZ263ml2pswIbDvFJgXO1bPAVWtNDkIbd4q1hKBqY18pqkcGjaCkYfgQcMG3Ecg0ogkAwFvQqzo24Q34+LKP32Bq8pu6EROojo0U7CzdJYDJ7ut63PnTNpPACS1Vs/UY4JqxHHrLS0t0dCLfjdJNMjvLz+FKY5K7/Gzp7ZvkTAqGGlk9fT2QU2oEmPxC9YWQqlwKf8UllV6df5lpSa+XpsIvUTRGNIWRENKOMxgGFIdWaUn5srdcpazFsOXvKhfwoYYmggKYk9CnDg0ysgfrF4auHX4mk5iQxFs0oc0YFb4KuSEJXZ9h5UAKnCpnu8DVXaEAZm2mAOoXjKeWWllKpsMH7tmTkoemr9YV/qfJ4wZt7mtBvb0qQZh2Z0mgHgpLjcGrnngPc/t5NNV+eNDYeDxcoQkmFn2bTprNOcPmlydTgjbl7/91bG4uf2QL3yV/tNi6fGYJJWUmxlzj2rmZwC8sfyASt5m1HjRIKQq8gU+7lBQq9rmOBWuhHBqeCDWDhcArVBpfbAlp0Ucewkpm04TFeNKQ3y+DLG51IspJz4NpiWqEZ+tfn8xQbs0lDf50zSgX61O8Pu3Lcx44nFkdbUUwV26W/iYaYFRS5dKLrqlDEZxwPTXxMqJdWnKBSM2SITB6ktprAWwFxsDtucHOSA0aeINQfCmkj4GAsl2e1EVuy9OzQ3DFEfgqareX+ivWEi6b9TXpmiXnVN2fVMKB70O94uDUpelwZbefka5HqY5SoR4anu2fOYOajVsCOxJRZbcRZiWpuWBSA=
  template:
    metadata:
      name: studylife-registry-auth
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
