---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: studylife-git-auth
  namespace: flux-system
spec:
  encryptedData:
    password: AgAz/U7WjeR/FNRIho8F/BOHCyizFeFuFkOdbWxpSC+sw2W/Fo6+zKg2VpaP++AWhTvgQ5tMINIHud/vvSc8v/b3HObx0wZFJ/es9icjD7aJxIF6z7tnoYgK6FoZ0EkGBllj8jZaQrlxJLYzzQvstT0VTbJHBZCaO6Ph+JmyD8Q6ohRKj4uuA0UoDlVl1YDN6bkD+mLJ5Fg0IVAph+0vuks1W2A41Aa9wgNiIhmOfGWUMhHn46WEUtDoQI2Ouseb5ZVDwtzBiCJEtGg1xDPceelbfFi5Hf1I7Yn9l9zZt37BgS2VD0nTUG8F7kQtiM/15iWfTVuM0bqWBPUf9SRYm7mDQcnn6zzMG3dTinm7aPpPLZp1YxMXPWIBv2guIzPUDNR4E46fbmNryf3wNoZiJ5BJ/S8uxIQBmzc6TuuOUE7niADsWtWAHsYD0mHyYvOU5tIcfq+JAD0gUeAUzS8LTja+rLyVIhp6e5n/T2F2yv7fYmj8GGgqFoRgSnebi7UzqKPqYS5LDkTwedUUjj8X4ATbawo/gdrc6cFdoGmPVx+2LsiFGi5MBLZDGGNk6Jz9a23SDMxoaFvZMWEx/0S4Yl4xrbtbSCLZh8q+XO+fgtS955eF5DUxVB4vBRRq+CXqvYYYYBXRNYQfEjeCarZ229FUO9eJL86xSztbDYz7/2RigIPa6V8oJg+pQa+Q4ikJ4lgSrK4sg+kgUz2leWPpS3brIyZNQZ8Ca9CgIKbq9OCoLHgbGmH1Ig+MiHR54qqFzFCy5ko=
    username: AgBX9wBnodpvpj5l1tLcA8ADlSvUWK78f9cJrbeblWx1t95JnJByJIzCMHIdInBpM7F1djAix0lLPz007vb8xC8qxvyM49pL63Z0WsCA6BW4yQk8T4lwA3xo6wWUkiCmsrBzPriKB4GYx+CsAgmX29HbbUky7qe//pp0n8In7L572CFmpgqJtm7YD4OVYtpxc22EHhP+YINOTdH0qhhI4HXe/b8Z9FZ8sV3MlkFAG54jM+e6yo2vdt7sXdg4MmaEF2Y4SuskPXVZ0hq2gXxD+NwnS90fB44ntHzsS77/JK2ibyv8tjJZ9unpAhNWbfMeERJC8CfVPgiHggiTljD7dXXneKieBJAQ4lietft5hU1VAyhs4rOjxPc/+ylJYbdufEWydgau7ZDq/lHmFXRKisquKQD5tS/elhkE49jdFmYyCpdLFkjr4oy7QriAk/6zUgh3wC/bUmr+RWX9NOKUlju38nMGQlPJJuAb0W9lQOoJrB6YqD671VzSfAeKpemPkR6KlS08VcGFwzIaHH1CC/+HZqHD9eJmWRD8rNUFdypT1DFVPgJGke1iiX7N6H9kwKeWDjp5xf76IgEiFGL1XVKdVi4oZ0JmeMgAUTiMsRgxx47D9TNKOTBOuSNTwRF/mE/5qqd3c0mIeJZCOpzexddC/mcCPSTqxcbt79LZTk9rQYtLAXKM2vYEL6NWISAtN4iaTqlvz6dWHC0UyepKyLtqpdrT5NstutkfXzVNLgCEfYYo9/98zjSl+6g9iBKx
  template:
    metadata:
      name: studylife-git-auth
      namespace: flux-system
    type: Opaque
