---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: r2-backup-credentials
  namespace: studylife-scale
spec:
  encryptedData:
    ACCESS_KEY_ID: AgCnNat/LYXWj9L+8hn029mNDA4dONMUd8D1J1mZhWSEhNPd4sjHVw8/vhg+aJACK9uyXUDvGECmoH1xvWM7qA8fc+LXKFSIDrbDqd7SdAOJG3j2xs4fHZpR0lZLVb6dj8OW0XAZg+pfGyh3VTvBFpl1SoL4k0R7RZh+5FoAHfrSV0QzUbLp7NIz2mfCfos3Dt8RkC/D31hl5wvHjHbHSHYePPVbMKXnwCAEHf42CE3FKGFdPsKvDfhb0zCYLxihIlgxwFkyO64KXJz25ceLupnH6IKEgmG0oER92YzbGJyJU/YI7sWgxWv2YrDBvQJ1BG375YS6kw8Af2gIWFpNLgyoaXWpUeHPlik/eW4H4FZ9bDPLQdOzqhI4MMiVqg/l4CJFn7xVJVsFfERXSi1pnn4BTGIEpGCbI7ZZV0M0EJCo/z8+1gpouMV+K+0Wpp6tv+vTz2URsamOy/Vca1C8lKIslSo/2XEPz3SajGOMOTPuuQNrM9s67LPHOIG8FINafW8ISAcyfdXNGHBEXTZVOChelfTKUZbkAYQTsDUsJPf22nitEn0zIPrS02+qY8sg0+4M4o/9gvPZPTLaZU00j2uykhzKH4zhrbfwvQ/bSJr6H+inifLFda7lJneENzEqAEB72Wc0L+/MrDz4zEbSrxZ7zMnfCz+U0wR4JND4cpyYcYBrYklDGRCfeB+iUQHLbXapsXrIqGHrhN7Zq41Zjf8DJ68QroR507gK8GKfTXv6cg==
    ACCESS_SECRET_KEY: AgB1Qt3egSpNyRaERJixSuIpEnZO2I+P32y7jHd2j/sj+ECjw0iUSZ+wLgAsz71HpeAWjBBHyoXZOPVRO4CUk6IEPs38GS2hJarIFQg5ysKpFxl5DzFL2OT/bPOtggWLvsIy3jIBLYAws8giHoIi4Pw+pcZpKugaH9nPnj0KmW+oOkz5EQ2OWR5Swlu8F5FmE7CYVCrzq2eshyiOiHoWYCqLwBKx4fwCpJtoBBQH2AV4hTdTULR7ABaj1qAhnvjO4pa+fRI+ZLc5qh5gf38jtsY4bUsqQmCJnCKEQHuvBsj37glzJ6hBaWXwFiufE4//+HExFTfNJj7jD2D5idgmnXSRekHNACJNgMzSWRC6icmtXJ40uv6XkNEdH+rG9hu5yAIcnmOjr7G4iGdJt303ZTuXl+CPHSDLuF23usofi7Sg+bZfvPVloT+zUMAfrxJIZYFuZRgP5pPn7fh7m3HOZLcBOosNpxz0dFDJav4SX+MKdO7I0Tj1FKKAmf3Z5ODf3kmKPv+OJXBFPu73LUeILqaokkEl31RR4/fUzU/IA15k794Ra/DU2pMVNoXAyMpA0UDXZDFUJkPvZWRI/feNVA8X9k+IXukzbZ8yvZpZu4bSJAf9zDm/pi7oJSMaUW79LnqRQw4StCtct0ogfQcR69tgpT8spWHx7NZhMaByNw9Pm0+J/5RlQ81EyzdAgRbNVrcOK3AJz2iWIqV63i7pzdrphdKOsnmEx2fu7CtK5qKaXmzuYiVWBWxa+HZVkEzuv6MzA2yFst5mehI7wMirLbBO
  template:
    metadata:
      name: r2-backup-credentials
      namespace: studylife-scale
    type: Opaque
