---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-auth
  namespace: studylife-scale
spec:
  encryptedData:
    password: AgC4hXVWHTnvCPR0whupxxUjsJwOmdB0V9upf9/6PDsbeLA1piPGsTkqVWOgUTqu6EfsnS5v+kB5Zneazf7EueZRfDTCo0sQEsRSm6h699W5d7KG5wQp8fcEJT1iVYDMjrKFRWB2RdpWPI7d48yxgF67IwsgMBHrIMAZ1nfLI+PpatHVM+fNxC0y1iUlX7SRALsh1jG/TbbZUIAMU0UgXzEe09sYhh5QXMW5AXWooymafrlnHHZ+yH1dxiA3EZ8y3z0mMtiFYVX3hPlJzLXDBH95ptlAtnrIPPk3vFXn2uC3RN6L7uyLE45CIjbvwpjmRzxxsRirKBsXpbDLtVO8TH0hI9jYl6lFPZ4f7H6+6NExQFuePJvMzv/PpjPiXbGuwZkyT5T894yAVGtrvZMQSiJmUk+yeWVSETj2p774fqdzHxiCVssYARRCQSessa37rZoyOE+7uK6r9ODsGYJdcNv9e5GP9Nacb6QYhyVSTtYzQ1+0kpBlvjfAJkPYg/pgl1IVE098S+PMtR6DvVHamqb9Thv6Qd4ujSPHixbhuhvmEcw+HqEpvlhcaBDH7MJq0MGDl/zR0TlA7UbgRAnGfRQEhwtHbq0d6LbXJGdkXZypqUyQ/9nO0LUV+uoZaLHHPGe9TwmlQdlZ8Vw3wLiGr4649T7mJW6gHJntqisDAw0qARR2fCZ+lsjK1k+8ic59lY0c6Y/TCvBLd4LAGy4SvnJTiqMZXjvrIUrebMJhtAW0KNcH7+rd/fbL/LrVdqrlY54=
    username: AgBMWt5FC+inFJU8sakeRSUgINA5dK50TQxnCeIKQoNH0PcwJLIZ/1RE6EN1LuG1Fl7+Wd1AXR0odax7AmlYWL/Xnx6QvIDETk0JqaMOEu/rWmSYCFdB+aVGaUSeGQrNLuEtDLTybKjhNxP/cMKvZkCyPldxV/6SfZwfQluV4041199vOWHChX0Z7hLiUqK6hXPCtNAxH3W0kXr4Dnajr0DAQNThdqohiUu0ofM0FbtnMwpn2ReaJS8W3+yiiflXDb/N6CJrFqlFS26MlaFMeCvdClQgyrkCy3LIUi6s1V/CCNQ7wMIPjzj1aqCtPMluBMPyzTQScqPqVd1g7lMJUQviE/sMcxIbXs5HEOnZCN0SNhxLQCQlo50AmGNtqDuEbsvhSmvOIKWDSUgFz0wYmFohr07RcGq8s4BaP2J1AxyhqwIG598BSSm0xUAiOt47iGzqokdlm2FzxsTA4P9MpmWmnaMdxw2QW0m2zwo/4zeAkksoqpogXOMJ6unvdXEtTy/OXUimJWIhIKWOlSxxp5XK651IcmhnxcQ3YdGYka2Qv740jnO1zKpf+vix5rT8zsm8p73I0jxVsRUlgza3CNO2mV01In9nMLrRU4O6mKnHjBULpUZlResZ9DdZrpBrZPQmvSFwwVViJTscz1UZBuKnrSftvbWn1W7iL7JHXrVofuOwZlq/l8MsMM7QvPFVfDRhT455DKjLDnM=
  template:
    metadata:
      name: redis-auth
      namespace: studylife-scale
    type: Opaque
