---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: studylife-pg-app-secret
  namespace: studylife-scale
spec:
  encryptedData:
    password: AgAPtLb/hk9fNeWtPVIyWjmmDPKNP9CkP6zLo+UsOIoWCFsM7IeVVJ06sjjhvk5YnJFT5VG+BMY0PpWi0ZmchoVrpQR+e9OXphlc1/9b6h4zbDmNyL6Or6B/4twrxv/UfQg0Bh7757Lgx6WjrehbR30cSrP7Ae2lAeF/hhLHozK8+JBItizabwdEvfFU2l6aX0R/DlbFzEjFNqw5iVBW8zwapxpUbyKYAHcnL0wVtde2gYCY8Rydo++YvV/sq+CKmWB2SDSUEZyWUOHEHGJeyLU76ctJL28qmifSWJeonJ0ohaAafT2WGR5WptnBcUQ55PCKeSqMKfpGDLpdus3pkQYrShMYa1JjzLhLoIEPfDRjy7dGutDo3P4A9kwyewigX7BrR8K2lkE3IcuK2fLVpI7nsmFU6jbhfR5Uyecbz4XR6pTtHgqfWxOBkKt4XKF1qSbEYV5lvDAAygivqBBpkQPdpDlvLHUw0jYpTTjgnuNxmfBFXTh+9jAKwDtEA/uEzT0VZKwExg3LwhBCIJCSPflScSOqRMhiBWDx+gSNtz75gdZwqUUFLnBIXu6GDNx23N2e7C5SzStnOu6z6ZnWvbRi/NeMyvZIqhgLqmkD8ddxlxg4+O7SMzO96x8fUtukb/Peb//6ZOOYcwfq6wEZ18zTv9nvxBfrhHEA+Kq/i9kTPcZ7zApWnXF6Qhgms3/wRr8sLcXKuww6VIW8o2Lcv0o65hpVgcOJ0CM=
    username: AgAdwrZR7VaE/Hh6UGIocH5dEPtUI2ALDeBi0wbg2lszfwAVcJYPGOT7fRO5G/2MQu7cHjJecQTDe2dUZAKirkKUIqkUYlz60i6CAJUssBU+1sP4dDAuQU0HgfKpZ/uTmUbGhmRwE8TF/x4J78eLnu5ZOKxjnMRqGZzhxyk1w3oFf9Jl+wG0PBnV1F2ZIFWLCnfG37DcW56MmLtCaNZtYhYd49AaiUaIaAEYHcKq7OHfw7Mifz76dpQ5gjSY1FL5W1COCOMPI+y4hPCVMFMu00HBsYkazsthv/9SY7jShbGjKa60e+jKJM/YWrwNujhyFuz7xDJdEHsMWy1ovV1osY1ArtzpzIl1SEDrCRdN8ETV2I7dIFwBldh4A7sv9VptN0C4KdiwrpE6uANUiaDpgdwdu8d1zZywajYruTcGBHnLj1fIm9HvuF85NRrflhVjol/t3/nu9y9WQYGTIYcki+Wffav5FczgRmz6yGDZS4Q4zi/+xF5l0rm1Y13yq+G5bU250TKq8ZS49Aiw9qWDqnc18u25Ox3Z+1WDIk7GJcfJJAkMD94+LFJ+oFlOeRf6KCW+Ub+DJoMTqMmr+5ArEb6qf8BAtV+LiWo7wLEjC0dVt5XdISm0vyKyoXFWrwSjrStQau4bIIM8VVaG+sR2L5JjX9wyc94nFU7XILGuMbiRcsJRAFsfqPvJ60ZLCvR3ys4Xdy5h+FcZMZc=
  template:
    metadata:
      name: studylife-pg-app-secret
      namespace: studylife-scale
    type: Opaque
