// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudyLife.Server.Data;

#nullable disable

namespace StudyLife.Server.Migrations.Postgres
{
    [DbContext(typeof(StudyLifeDbPostgres))]
    [Migration("20260903115722_AddHotPathIndexesPostgres")]
    partial class AddHotPathIndexesPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudyLife.Server.Data.AiKeyOutboxEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AiApiKeyPlaintext")
                        .HasColumnType("text");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("LastAttemptAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.ToTable("AiKeyOutbox");
                });

            modelBuilder.Entity("StudyLife.Server.Data.AuthInviteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("UsedByUserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AuthInvites");
                });

            modelBuilder.Entity("StudyLife.Server.Data.AuthSessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("HardExpiresAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("LastUsedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("AuthSessions");
                });

            modelBuilder.Entity("StudyLife.Server.Data.AuthUserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AiApiKeyCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("AiApiKeyHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ApiKeyCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ApiKeyHash")
                        .HasColumnType("text");

                    b.Property<string>("CalendarToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CalendarTokenCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("CaptureApiKeyCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CaptureApiKeyHash")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("DeveloperApiKeyCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DeveloperApiKeyHash")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FocusGuardApiKeyCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FocusGuardApiKeyHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FocusTunesApiKeyCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("FocusTunesApiKeyHash")
                        .HasColumnType("text");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("McpApiKeyCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("McpApiKeyHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TrayApiKeyCreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("TrayApiKeyHash")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AiApiKeyHash")
                        .IsUnique();

                    b.HasIndex("ApiKeyHash")
                        .IsUnique();

                    b.HasIndex("CalendarToken")
                        .IsUnique();

                    b.HasIndex("CaptureApiKeyHash")
                        .IsUnique();

                    b.HasIndex("DeveloperApiKeyHash")
                        .IsUnique();

                    b.HasIndex("FocusGuardApiKeyHash")
                        .IsUnique();

                    b.HasIndex("FocusTunesApiKeyHash")
                        .IsUnique();

                    b.HasIndex("McpApiKeyHash")
                        .IsUnique();

                    b.HasIndex("TrayApiKeyHash")
                        .IsUnique();

                    b.ToTable("AuthUsers");
                });

            modelBuilder.Entity("StudyLife.Server.Data.ClientApiKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("GrantedScopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("ClientApiKeys");
                });

            modelBuilder.Entity("StudyLife.Server.Data.CourseGoalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("CompletedTopics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompletionNote")
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("numeric");

                    b.Property<string>("Tag")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId", "CourseId")
                        .IsUnique();

                    b.ToTable("CourseGoals");
                });

            modelBuilder.Entity("StudyLife.Server.Data.CourseGroupEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<int>("EctsQuota")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("CourseGroups");
                });

            modelBuilder.Entity("StudyLife.Server.Data.CourseResourceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseResources");
                });

            modelBuilder.Entity("StudyLife.Server.Data.CustomCourseEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CourseGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("Ects")
                        .HasColumnType("integer");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("StudyProgramId")
                        .HasColumnType("integer");

                    b.Property<string>("Topics")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("StudyProgramId");

                    b.ToTable("CustomCourses");
                });

            modelBuilder.Entity("StudyLife.Server.Data.NoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("EnrichedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EnrichmentAttempts")
                        .HasColumnType("integer");

                    b.Property<bool>("IsMarkdown")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastEnrichmentAttemptAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("RelatedNoteIds")
                        .HasColumnType("text");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId", "CourseId");

                    b.HasIndex("AuthUserId", "UpdatedAt");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("StudyLife.Server.Data.OAuthClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedRedirectUris")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OwnerAuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("RequestedScopes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientId")
                        .IsUnique();

                    b.HasIndex("OwnerAuthUserId");

                    b.ToTable("OAuthClients");
                });

            modelBuilder.Entity("StudyLife.Server.Data.PasskeyCredentialEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("CredentialId")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("DeviceLabel")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<byte[]>("PublicKey")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("SignCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CredentialId")
                        .IsUnique();

                    b.ToTable("PasskeyCredentials");
                });

            modelBuilder.Entity("StudyLife.Server.Data.PushSubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApnsToken")
                        .HasColumnType("text");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId", "Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("StudyLife.Server.Data.RecoveryCodeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodeHash")
                        .IsUnique();

                    b.ToTable("RecoveryCodes");
                });

            modelBuilder.Entity("StudyLife.Server.Data.SentReminderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId", "Key")
                        .IsUnique();

                    b.ToTable("SentReminders");
                });

            modelBuilder.Entity("StudyLife.Server.Data.SessionTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CourseColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan?>("DefaultStartTime")
                        .HasColumnType("interval");

                    b.Property<int?>("DefaultWeekday")
                        .HasColumnType("integer");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.ToTable("SessionTemplates");
                });

            modelBuilder.Entity("StudyLife.Server.Data.StudyProgramEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.ToTable("StudyPrograms");
                });

            modelBuilder.Entity("StudyLife.Server.Data.StudySessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<string>("CourseColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("RecurrenceGroupId")
                        .HasColumnType("text");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TimerModeId")
                        .HasColumnType("integer");

                    b.Property<string>("Topic")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId", "StartTime");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("StudyLife.Server.Data.SystemSecretsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SetupSecretCode")
                        .HasColumnType("text");

                    b.Property<string>("VapidPrivateKey")
                        .HasColumnType("text");

                    b.Property<string>("VapidPublicKey")
                        .HasColumnType("text");

                    b.Property<string>("VapidSubject")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SystemSecrets");
                });

            modelBuilder.Entity("StudyLife.Server.Data.TimerStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("integer");

                    b.Property<bool>("IsBreak")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("boolean");

                    b.Property<long?>("LastClientSequence")
                        .HasColumnType("bigint");

                    b.Property<string>("LiveActivityPushToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PhaseEndsAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("SessionId")
                        .HasColumnType("integer");

                    b.Property<int>("TimerModeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("TimerState");
                });

            modelBuilder.Entity("StudyLife.Server.Data.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AchievementNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int?>("ActiveStudyProgramId")
                        .HasColumnType("integer");

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoSwitchFocus")
                        .HasColumnType("boolean");

                    b.Property<int>("AutoSwitchMinutesBefore")
                        .HasColumnType("integer");

                    b.Property<bool>("BestStudyTimeRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ComebackNudgeEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CompletedCourseIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CourseAlmostDoneRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CourseGoalReminderDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("CourseGoalRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("CustomTimerModes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("DailyMotivationEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("InactivityRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("InactivityThresholdDays")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastBackupDownloadAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MonthlyGoalMaxHours")
                        .HasColumnType("integer");

                    b.Property<int>("MonthlyGoalMinHours")
                        .HasColumnType("integer");

                    b.Property<bool>("MonthlyReportEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MotivationalStyle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("NewRecordNotificationsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("PerCourseInactivityRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("ProgressShareEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("ProgressShareToken")
                        .HasColumnType("text");

                    b.Property<string>("SelectedCourseIds")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SessionReminderMinutes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SessionRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("StreakRiskRemindersEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("StudyDays")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudyWindowEndHour")
                        .HasColumnType("integer");

                    b.Property<int>("StudyWindowStartHour")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("TargetGraduationDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyGoalMaxHours")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyGoalMinHours")
                        .HasColumnType("integer");

                    b.Property<bool>("WeeklyGoalNudgeEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("WeeklyReportEnabled")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("StudyLife.Server.Data.WebhookApiKeyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthUserId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.ToTable("WebhookApiKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
