// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudyLife.Server.Data;

#nullable disable

namespace StudyLife.Server.Migrations
{
    [DbContext(typeof(StudyLifeDb))]
    [Migration("20260714120000_AddNotificationToggles")]
    partial class AddNotificationToggles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("StudyLife.Server.Data.CourseGoalEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletedTopics")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CompletionNote")
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Grade")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tag")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("TargetDate")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.ToTable("CourseGoals");
                });

            modelBuilder.Entity("StudyLife.Server.Data.NoteEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("StudyLife.Server.Data.PushSubscriptionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Endpoint")
                        .IsUnique();

                    b.ToTable("PushSubscriptions");
                });

            modelBuilder.Entity("StudyLife.Server.Data.SentReminderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("SentReminders");
                });

            modelBuilder.Entity("StudyLife.Server.Data.StudySessionEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecurrenceGroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimerModeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Topic")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("StartTime");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("StudyLife.Server.Data.TimerStateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CurrentRound")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBreak")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("PhaseEndsAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("SessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TimerModeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TimerState");
                });

            modelBuilder.Entity("StudyLife.Server.Data.UserSettingsEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AchievementNotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoSwitchFocus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoSwitchMinutesBefore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CompletedCourseIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseGoalReminderDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CourseGoalRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomTimerModes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("InactivityRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("InactivityThresholdDays")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyGoalMaxHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MonthlyGoalMinHours")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MotivationalStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SelectedCourseIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionReminderMinutes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("SessionRemindersEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudyDays")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StudyWindowEndHour")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudyWindowStartHour")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("TargetGraduationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WeeklyGoalMaxHours")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeeklyGoalMinHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WeeklyReportEnabled")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });
#pragma warning restore 612, 618
        }
    }
}
